baseurl = "https://onlineheadlines.net"
languageCode = "en-us"
title = "Headlines"
theme = "hugo-xmag"
googleAnalytics = "UA-177767171-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 30



[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Second Headlines"
    url = "/second_headline/"
    weight = 2
[[menu.main]]
    name = "Fringe"
    url = "/fringe/"
    weight = 3
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    summary_length = 300
    github_edit = "https://github.com/yihui/hugo-xmag/edit/master/exampleSite/content/"
    footer = "[Github](https://github.com/stevezieglerva/headlines) | [hugo-xmag Theme](https://themes.gohugo.io/hugo-xmag/) "

[params.text]
    truncated = "&hellip;"


